name: CodeQuality Dynamic Code Analysis Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get install valgrind
        sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
    - name: make test
      run: make -C 3_Implementation/ test
